### ISSUE TITLE
Criar validação de data

### ISSUE THREAD

**Issue by igorthurler** [pauloanalista/prmToolkit.NotificationPattern#1]
Possibilitar a verificação de uma data. IfInvalidDate por exemplo.

**Comment by pauloanalista** [comment]
Foi adicionado um novo método chamado 
IfNotDate

Só não segui o nome indicado devido todas as outras validações seguirem outro padrão.
Ex:
IfNotCpf
IfNotCnpj
IfNotGuid


Aproveitei e implementei novas regras para adicionar notificação
- IfNotDate
- IfNullOrOrInvalidLength
- IfLengthGreaterThan
- IfLengthLowerThan

Houve ajustes nas mensagens padrões também.
