### ISSUE TITLE
The entity type 'Notification' requires a primary key to be defined.

### ISSUE THREAD

**Issue by deyvisonbrandao** [pauloanalista/prmToolkit.NotificationPattern#5]
Adicionei a validação na minha classe de entidade conforme abaixo, e no momento de gerar atualizar minha base de dados via migration (update-database), foi me retornado a seguinte mensagem: "The entity type 'Notification' requires a primary key to be defined."

using Imperium.Domain.Entities.Base;
using Imperium.Domain.Enums;
using Imperium.Domain.ValueObjects;
using prmToolkit.NotificationPattern;

namespace Imperium.Domain.Entities
{
	public class Company  : EntityBase
	{
		public string CompanyName { get; private set; }
		public string FantasyName { get; private set; }
		public Email Email { get; private set; }
		public string CNPJ { get; private set; }
		public Address Address { get; private set; }
		public EnumStatus Status { get; private set; }

		private Company()
		{
		}

		public Company(string companyName, string fantasyName, Email email, string cnpj)
		{
			CompanyName = companyName;
			FantasyName = fantasyName;
			Email = email;
			CNPJ = cnpj;

			new AddNotifications<Company>(this).IfNotCnpj(x => x.CNPJ);
		}

		public Company(string companyName, string fantasyName, Email email, string cnpj, Address address)
		{
			CompanyName = companyName;
			FantasyName = fantasyName;
			Email = email;
			CNPJ = cnpj;
			Address = address;
			Status = EnumStatus.Pendente;
		}
	}
}

using prmToolkit.NotificationPattern;
using System;
using System.ComponentModel.DataAnnotations;

namespace Imperium.Domain.Entities.Base
{
	public abstract class EntityBase : Notifiable
	{
		[Key]
		public Guid Id { get; private set; }

		protected EntityBase()
		{
			Id = Guid.NewGuid();
		}
	}
}

**Comment by thiagomoises** [comment]
Amigo, desculpe a demora pra responder rsrsr.
Então. Não recomendo que suas bases de entidade herdem as notificações. 
As notificações foram feitas para serem usadas nas classes de Transferência (DTO), em sua camada de domínio.
Tenta dar uma pesquisada sobre DDD, vai ajudar a entender um pouco melhor

**Comment by deyvisonbrandao** [comment]
Entendi, segui mais ou menos a mesma linha do projeto do próprio Paulo de um curso que fiz e nele a validação estava dentro da propria entidade. https://github.com/pauloanalista/Criando-Apis-robustas-em-C-

**Comment by deyvisonbrandao** [comment]
Posso estar enganado, mas no projeto do  [repositorio](https://github.com/pauloanalista/Criando-Apis-robustas-em-C-) esta sendo usado a validação na Entidade que é mapeada no banco de dados não???
A DTO não seria as classes dentro diretório Domain/Arguments (que são parametros dos métodos da API)?
